### ISSUE TITLE
运行plot_result.m文件进行结果可视化时报错

### ISSUE THREAD

**Issue by shenmimimi** [DrGabor/FPFH_Coarse_Align#5]
未定义函数或变量 'Loc2Glo'。
出错 plot_result (line 32)
aft = Loc2Glo(cloud_mov.Location', dR', dT);

**Comment by DrGabor** [comment]
你好，这个函数在LiDAR/CommonFunctions里

---原始邮件---
发件人: "shenmimimi"<notifications@github.com&gt;
发送时间: 2020年8月15日(周六) 上午9:18
收件人: "DrGabor/FPFH_Coarse_Alignment"<FPFH_Coarse_Alignment@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [DrGabor/FPFH_Coarse_Alignment] 运行plot_result.m文件进行结果可视化时报错 (#5)




 
未定义函数或变量 'Loc2Glo'。
 出错 plot_result (line 32)
 aft = Loc2Glo(cloud_mov.Location', dR', dT);
